### ISSUE TITLE
Patches are out-of-date

### ISSUE THREAD

**Issue by sudoBash418** [Leonidas-from-XIV/aur-homeshick-git#1]
Is this still being updated?
It seems that the patches don't work anymore due to upstream changes.
For example, /usr/bin/homeshick still points to "$HOME/.homesick/repos/homeshick" instead of the expected "/usr/lib/homeshick"

**Comment by Leonidas-from-XIV** [comment]
Yes the guys keep on moving locations with just about every commit. I don't see the breakage because I install it once and then no more.

Patches, uhm, welcome.

**Comment by sudoBash418** [comment]
Ahh, okay.

I might send in a patch soon, but I've stopped using homeshick recently, so that's likely to be my last patch as well.

Looking at their Github repo, it kind of looks like development has either stopped or slowed to molasses since about the start of 2015. So hopefully it won't change all that much anymore.

I guess I'll close this then? Or maybe I should wait until it's updated... 

_Sent from my Lenovo YT-X703F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Leonidas-from-XIV** [comment]
That sounds good, thanks! I'm not using it much myself, I'm looking for a bit of a different solution, with a bit different choices.

**Comment by sudoBash418** [comment]
No problem.

And if you're interested, there's quite a list over on the ArchWiki at [https://wiki.archlinux.org/index.php/Dotfiles](https://wiki.archlinux.org/index.php/Dotfiles) if you haven't already seen it.

_Sent from my Lenovo YT-X703F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
